# Generated by Django 5.0.6 on 2026-09-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_source',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google OAuth'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='email', max_length=20),
        ),
    ]
