# Generated by Django 5.0.6 on 2026-08-27 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Untitled Resume', max_length=150)),
                ('source', models.CharField(choices=[('upload', 'Uploaded File (PDF/DOCX)'), ('linkedin', 'LinkedIn Import'), ('voice', 'Voice AI'), ('scratch', 'Built from Scratch'), ('tailored', 'Tailored Copy of Another Resume')], default='scratch', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'AI Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('professional_summary', models.TextField(blank=True)),
                ('raw_ai_extraction', models.JSONField(blank=True, null=True)),
                ('template_key', models.CharField(default='minimal-01', max_length=50)),
                ('base_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailored_versions', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('tech_stack', models.JSONField(default=list)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resumes.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedInImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin_profile_urn', models.CharField(blank=True, max_length=255)),
                ('raw_profile_snapshot', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_imports', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobTailoringRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_description', models.TextField()),
                ('job_title_guess', models.CharField(blank=True, max_length=150)),
                ('company_guess', models.CharField(blank=True, max_length=150)),
                ('match_score_before', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match_score_after', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('matched_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailoring_requests', to=settings.AUTH_USER_MODEL)),
                ('result_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume')),
                ('source_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailoring_requests', to='resumes.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resumes.resume')),
            ],
            options={
                'ordering': ['order', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skill'), ('tool', 'Tool / Software'), ('language', 'Language')], default='technical', max_length=20)),
                ('proficiency', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_storage_key', models.CharField(blank=True, max_length=255)),
                ('transcript', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('transcribing', 'Transcribing'), ('structuring', 'AI Structuring'), ('complete', 'Complete'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('bullet_points', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resumes.resume')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
