# Generated by Django 5.0.6 on 2026-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
