# Generated by Django 5.0.6 on 2026-09-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resumedownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedownload',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='resumes.resume'),
        ),
    ]
